allow packaging versions >=20.0
Othoz/gcsfs pull request #47
Opened 2021-12-30 23:37 UTC by ritiko

2021-12-31 13:16 UTC, mathiaseitz approved these changes

2022-01-11 05:01 UTC, ritiko commented
@trendelkampschroer just bumping

2022-01-11 07:27 UTC, trendelkampschroer requested changes

2022-01-11 07:27 UTC, trendelkampschroer commented on setup.py
> +            "packaging>=20.0",
Please use `"packaging>=20.0,<22.0"` instead.

2022-01-11 14:10 UTC, ritiko commented on setup.py
> +            "packaging>=20.0",
:+1:  Changed

2022-01-11 14:12 UTC, trendelkampschroer approved these changes

2022-05-12 10:10 UTC, closed without merging